version: '3.1'

services:

  mysql:
    image: mysql
    volumes:
      - ./mysqldbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      # MYSQL_DATABASE: nodemysql
      # MYSQL_USER: root
      # MYSQL_PASSWORD: toor
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_ARBITRARY=1

#   admin:
#         image: "phpmyadmin/phpmyadmin"
#         restart: always
#         ports:
#           - "8060:80"
#         links:
#           - mysql:db
#         depends_on:
#           - mysql
# volumes:
#   db: